# ============================================================
# Save as: noon_train.py
# Trains "Noon (ن)" vs "Not Noon"
#
# FOLDER LAYOUT (only what you have):
#   D:\MODEL\Sign_Speak_testing-main\Simple_Dataset\Noon\
#        └── *.jpg / *.png  (Noon-only hand images)
#
# Negatives are generated by DESTROYING the Noon pose via
# realistic transforms (curl/extend/shift/scale/rotate).
# ============================================================

import os, glob, json, random
import numpy as np
import cv2
import mediapipe as mp
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

print("=" * 60)
print("SIGNSPEAK - Noon (ن) Training [No not_noon folder]")
print("=" * 60)

# ========== CONFIG ==========
NOON_DIR   = r"D:\MODEL\Sign_Speak_testing-main\Simple_Dataset\Noon"
OUTPUT_DIR = r"D:\MODEL\Sign_Speak_testing-main\Exported_Model\exported_models_noon"
os.makedirs(OUTPUT_DIR, exist_ok=True)

IMAGE_WIDTH  = 300
IMAGE_HEIGHT = 300
RANDOM_SEED  = 42
random.seed(RANDOM_SEED); np.random.seed(RANDOM_SEED)

# ============================================================
# MediaPipe Hand landmark indices (for pose-based negatives)
# ============================================================
WRIST = 0
THUMB  = [1,2,3,4]
INDEX  = [5,6,7,8]
MIDDLE = [9,10,11,12]
RING   = [13,14,15,16]
PINKY  = [17,18,19,20]
FINGERS = [THUMB, INDEX, MIDDLE, RING, PINKY]

# ============================================================
# 1) EXTRACT LANDMARKS FROM NOON IMAGES
# ============================================================
print(f"\n📁 Scanning: {NOON_DIR}")
files = []
for ext in ("*.jpg","*.jpeg","*.png","*.bmp","*.webp"):
    files += glob.glob(os.path.join(NOON_DIR, ext))
    files += glob.glob(os.path.join(NOON_DIR, "**", ext), recursive=True)
files = list(set(files))
print(f"   Images found: {len(files)}")

if len(files) == 0:
    raise RuntimeError(f"❌ No images found in {NOON_DIR}")

mp_hands = mp.solutions.hands
HANDS = mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=1,
    min_detection_confidence=0.4,
    min_tracking_confidence=0.4
)

X_pos = []
skipped = 0
for f in files:
    img = cv2.imread(f)
    if img is None: skipped += 1; continue
    res = HANDS.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    if not res.multi_hand_landmarks:
        skipped += 1; continue
    lm = res.multi_hand_landmarks[0]
    feat = []
    for p in lm.landmark:
        feat.append(p.x); feat.append(p.y)
    if len(feat) == 42:
        X_pos.append(feat)

HANDS.close()
print(f"   ✅ Valid Noon samples: {len(X_pos)}  |  skipped: {skipped}")

if len(X_pos) < 5:
    raise RuntimeError(
        f"❌ Only {len(X_pos)} Noon images usable.\n"
        "   MediaPipe couldn't find a hand in your images.\n"
        "   → Use brighter, clearer images with one hand clearly visible."
    )

X_pos = np.array(X_pos, dtype=np.float32)
X_pos = np.clip(X_pos, 0, 1)
y_pos = np.ones(len(X_pos), dtype=np.float32)

# ============================================================
# 2) AUGMENT POSITIVES (small variations of real Noon)
# ============================================================
print("\n🔧 Augmenting real Noon...")
rng = np.random.default_rng(RANDOM_SEED)
augX, augY = [X_pos], [y_pos]

for _ in range(3):
    n = rng.normal(0, 0.012, X_pos.shape).astype(np.float32)
    augX.append(np.clip(X_pos + n, 0, 1)); augY.append(y_pos)

for s in [0.95, 1.05]:
    augX.append(np.clip(X_pos * s, 0, 1)); augY.append(y_pos)

for dx, dy in [(0.02,0),(-0.02,0),(0,0.02),(0,-0.02)]:
    Xs = X_pos.copy()
    Xs[:, 0::2] = np.clip(Xs[:, 0::2] + dx, 0, 1)
    Xs[:, 1::2] = np.clip(Xs[:, 1::2] + dy, 0, 1)
    augX.append(Xs); augY.append(y_pos)

X_pos_aug = np.vstack(augX); y_pos_aug = np.hstack(augY)
print(f"   Noon: {len(X_pos)} → {len(X_pos_aug)}")

# ============================================================
# 3) GENERATE NEGATIVES FROM THE NOON POSE
# ============================================================
# The Noon sign: index finger extended downward, other fingers
# curled. To make it "not Noon", we DISTORT the pose so that
# at least one of those properties is broken.
print("\n🔧 Generating negatives from Noon pose distortions...")

def build_negative(noon_pose, kind, rng):
    """Take a 42-vector Noon pose and return a corrupted version."""
    f = noon_pose.reshape(21, 2).copy()      # (x,y) per landmark

    if kind == "curl_index":
        # Curl the index finger toward the wrist → breaks "index extended"
        wrist = f[WRIST]
        for i in [6, 7, 8]:
            f[i] = 0.6 * f[i] + 0.4 * wrist

    elif kind == "extend_middle":
        # Extend the middle finger → adds a second finger up
        mcp, pip = f[9], f[10]
        direction = pip - mcp
        for i in [10, 11, 12]:
            f[i] = mcp + direction * (i - 8)

    elif kind == "extend_pinky":
        mcp, pip = f[17], f[18]
        direction = pip - mcp
        for i in [18, 19, 20]:
            f[i] = mcp + direction * (i - 16)

    elif kind == "extend_ring":
        mcp, pip = f[13], f[14]
        direction = pip - mcp
        for i in [14, 15, 16]:
            f[i] = mcp + direction * (i - 12)

    elif kind == "open_hand":
        # Push all fingertips away from wrist → spread fingers
        wrist = f[WRIST]
        for tip in [4, 8, 12, 16, 20]:
            f[tip] = wrist + (f[tip] - wrist) * 1.8

    elif kind == "close_hand":
        # Pull all tips toward the wrist → fist
        wrist = f[WRIST]
        for tip in [4, 8, 12, 16, 20]:
            f[tip] = wrist + (f[tip] - wrist) * 0.2

    elif kind == "flip_vertical":
        # Vertical flip of the hand pose
        f[:, 1] = 1.0 - f[:, 1]

    elif kind == "flip_horizontal":
        f[:, 0] = 1.0 - f[:, 0]

    elif kind == "rotate":
        angle = rng.uniform(-0.6, 0.6)          # ±34°
        c, s = np.cos(angle), np.sin(angle)
        cx, cy = f[:,0].mean(), f[:,1].mean()
        f[:,0] -= cx; f[:,1] -= cy
        f = f @ np.array([[c,-s],[s,c]])
        f[:,0] += cx; f[:,1] += cy

    elif kind == "scale_pose":
        s = rng.uniform(0.5, 0.7)               # much smaller hand
        cx, cy = f[:,0].mean(), f[:,1].mean()
        f = (f - [cx,cy]) * s + [cx,cy]

    elif kind == "random_jitter":
        # Medium-random pose (not like Noon at all)
        f = rng.uniform(0.2, 0.8, f.shape)

    elif kind == "noise_strong":
        n = rng.normal(0, 0.08, f.shape)
        f = f + n

    return np.clip(f.flatten(), 0, 1).astype(np.float32)

NEG_KINDS = [
    "curl_index", "extend_middle", "extend_pinky", "extend_ring",
    "open_hand", "close_hand", "flip_vertical", "flip_horizontal",
    "rotate", "scale_pose", "random_jitter", "noise_strong"
]

neg_X, neg_Y = [], []
# Generate ~20 negatives per real Noon sample
PER_SAMPLE = 20
for pose in X_pos:
    for _ in range(PER_SAMPLE):
        kind = rng.choice(NEG_KINDS)
        neg_X.append(build_negative(pose, kind, rng))
        neg_Y.append(0.0)

X_neg = np.array(neg_X, dtype=np.float32)
y_neg = np.array(neg_Y, dtype=np.float32)
print(f"   Generated negatives: {len(X_neg)}")

# ============================================================
# 4) BUILD FINAL DATASET
# ============================================================
X = np.vstack([X_pos_aug, X_neg])
y = np.hstack([y_pos_aug, y_neg]).astype(np.float32)
sh = rng.permutation(len(X))
X, y = X[sh], y[sh]
print(f"\n📊 Final: {len(X)}  |  Noon: {int(y.sum())}  |  Other: {int((1-y).sum())}")

# ============================================================
# 5) SPLIT
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.15, random_state=42, stratify=y_train)
print(f"✂️ Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

cw = compute_class_weight('balanced', classes=np.array([0,1]), y=y_train)
cw_dict = {0: float(cw[0]), 1: float(cw[1])}
print(f"⚖️ Class weights: {cw_dict}")

# ============================================================
# 6) MODEL
# ============================================================
print("\n🏗️ Building model...")
model = Sequential([
    Dense(256, activation='relu', input_shape=(42,)),
    BatchNormalization(), Dropout(0.5),
    Dense(256, activation='relu'), BatchNormalization(), Dropout(0.5),
    Dense(128, activation='relu'), BatchNormalization(), Dropout(0.4),
    Dense(128, activation='relu'), BatchNormalization(), Dropout(0.4),
    Dense(64,  activation='relu'), BatchNormalization(), Dropout(0.3),
    Dense(32,  activation='relu'), BatchNormalization(), Dropout(0.3),
    Dense(16,  activation='relu'), BatchNormalization(), Dropout(0.2),
    Dense(1,   activation='sigmoid')
])
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)
model.summary()

# ============================================================
# 7) TRAIN
# ============================================================
print("\n🚀 Training...")
cbs = [
    EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=12, min_lr=1e-7, verbose=1),
    ModelCheckpoint(os.path.join(OUTPUT_DIR,'best_noon.h5'),
                    monitor='val_accuracy', save_best_only=True, verbose=1)
]
model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=200, batch_size=32,
    callbacks=cbs, class_weight=cw_dict, verbose=1
)

# ============================================================
# 8) EVALUATE + FIND BEST THRESHOLD
# ============================================================
print("\n📊 Evaluation:")
_, tr_a, tr_auc = model.evaluate(X_train, y_train, verbose=0)
_, va_a, va_auc = model.evaluate(X_val,   y_val,   verbose=0)
_, te_a, te_auc = model.evaluate(X_test,  y_test,  verbose=0)
print(f"   Train: Acc={tr_a*100:.2f}% AUC={tr_auc:.4f}")
print(f"   Val:   Acc={va_a*100:.2f}% AUC={va_auc:.4f}")
print(f"   Test:  Acc={te_a*100:.2f}% AUC={te_auc:.4f}")

val_preds = model.predict(X_val, verbose=0).flatten()
best_thr, best_f1 = 0.5, -1
for thr in np.arange(0.40, 0.991, 0.01):
    tp = ((val_preds > thr) & (y_val == 1)).sum()
    fp = ((val_preds > thr) & (y_val == 0)).sum()
    fn = ((val_preds <= thr) & (y_val == 1)).sum()
    prec = tp / (tp + fp + 1e-9)
    rec  = tp / (tp + fn + 1e-9)
    f1   = 2*prec*rec / (prec + rec + 1e-9)
    if f1 > best_f1:
        best_f1, best_thr = f1, float(thr)

print(f"\n🎯 Best threshold: {best_thr:.2f}  (val F1 = {best_f1:.3f})")

noon_preds = model.predict(X_pos, verbose=0).flatten()
recall = (noon_preds > best_thr).mean()*100
neg_preds = model.predict(X_neg[:3000], verbose=0).flatten()
fp_rate = (neg_preds > best_thr).mean()*100
print(f"   Real Noon recall    @ {best_thr:.2f}: {recall:.1f}%")
print(f"   False-positive rate @ {best_thr:.2f}: {fp_rate:.2f}%")

# ============================================================
# 9) SAVE
# ============================================================
print("\n💾 Saving...")
model.save(os.path.join(OUTPUT_DIR,'noon_robust.h5'))
conv = tf.lite.TFLiteConverter.from_keras_model(model)
tfl = conv.convert()
with open(os.path.join(OUTPUT_DIR,'noon_robust.tflite'),'wb') as f:
    f.write(tfl)
print(f"   TFLite: {len(tfl)/1024:.1f} KB")

info = {
    'letter': 'ن',
    'input': '42 MediaPipe landmarks (0-1)',
    'threshold': best_thr,
    'test_accuracy': float(te_a),
    'test_auc': float(te_auc),
    'noon_recall': float(recall/100),
    'fp_rate': float(fp_rate/100),
    'num_noon_train': int(len(X_pos)),
    'num_negatives': int(len(X_neg)),
}
with open(os.path.join(OUTPUT_DIR,'noon_robust_info.json'),'w',encoding='utf-8') as f:
    json.dump(info, f, indent=2, ensure_ascii=False)

print(f"\n✅ DONE — Test Acc={te_a*100:.2f}% | Recall={recall:.1f}% | "
      f"FPR={fp_rate:.2f}% | Threshold={best_thr:.2f}")